import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
	compileMemoryMd,
	loadGoldenTasks,
	parseArgs,
	parseGoldenTask,
	summarizeTask,
	totalTokens,
} from "../src/bench.js";
import {
	getBaseline,
	openDb,
	recordBaseline,
	type WardenDb,
} from "../src/db.js";
import { DOMAIN_AGENTS } from "../src/types.js";

describe("parseArgs", () => {
	it("parses agent, rule, runs, and task", () => {
		expect(
			parseArgs([
				"--agent",
				"sql",
				"--rule",
				"7",
				"--runs",
				"3",
				"--task",
				"sql-01",
			]),
		).toEqual({ agent: "sql", rule: 7, runs: 3, task: "sql-01" });
	});

	it("defaults to two runs and no rule", () => {
		expect(parseArgs(["--agent", "backend"])).toEqual({
			agent: "backend",
			rule: null,
			runs: 2,
			task: null,
		});
	});

	it("rejects unknown agents, flags, and bad runs", () => {
		expect(() => parseArgs(["--agent", "main"])).toThrow(/--agent/);
		expect(() => parseArgs(["--agent", "sql", "--frobnicate", "1"])).toThrow(
			/unknown flag/,
		);
		expect(() => parseArgs(["--agent", "sql", "--runs", "0"])).toThrow(
			/--runs/,
		);
	});
});

describe("golden task files", () => {
	it("parses frontmatter fields", () => {
		const task = parseGoldenTask(
			'---\nid: x-01\nagent: sql\nprompt: "Do the thing."\nsuccess_check: "true"\n---\nbody',
			"x.md",
		);
		expect(task).toMatchObject({
			id: "x-01",
			agent: "sql",
			prompt: "Do the thing.",
			successCheck: "true",
		});
	});

	it("rejects files missing required fields", () => {
		expect(() => parseGoldenTask("---\nid: x\n---\n", "x.md")).toThrow(/agent/);
		expect(() => parseGoldenTask("no frontmatter", "x.md")).toThrow(
			/frontmatter/,
		);
	});

	it("every shipped agent has exactly three valid golden tasks", () => {
		for (const agent of DOMAIN_AGENTS) {
			const tasks = loadGoldenTasks(agent);
			expect(tasks, agent).toHaveLength(3);
			for (const task of tasks) {
				expect(task.agent).toBe(agent);
				expect(task.id).toMatch(new RegExp(`^${agent}-\\d+$`));
				expect(task.prompt.length).toBeGreaterThan(20);
				expect(task.successCheck.length).toBeGreaterThan(0);
			}
		}
	});
});

describe("compileMemoryMd", () => {
	it("renders the generated header and one rule per line", () => {
		const memory = compileMemoryMd([{ body: "Rule A" }, { body: "Rule B" }]);
		expect(memory).toContain("GENERATED BY token-warden");
		expect(memory).toContain("- Rule A\n- Rule B");
	});
});

describe("totalTokens", () => {
	it("sums all four token counters", () => {
		expect(
			totalTokens({
				inputTokens: 1,
				outputTokens: 2,
				cacheCreation: 3,
				cacheRead: 4,
			}),
		).toBe(10);
	});
});

describe("summarizeTask", () => {
	it("averages completed runs only and flags >25% variance", () => {
		const summary = summarizeTask("t", [
			{ sessionId: "a", tokens: 100, completed: true },
			{ sessionId: "b", tokens: 200, completed: true },
			{ sessionId: "c", tokens: 9999, completed: false },
		]);
		expect(summary.meanCompletedTokens).toBe(150);
		expect(summary.highVariance).toBe(true);
	});

	it("does not flag close runs", () => {
		const summary = summarizeTask("t", [
			{ sessionId: "a", tokens: 100, completed: true },
			{ sessionId: "b", tokens: 110, completed: true },
		]);
		expect(summary.highVariance).toBe(false);
	});
});

describe("baseline freezing", () => {
	let dir: string;
	let db: WardenDb;

	beforeEach(() => {
		dir = mkdtempSync(join(tmpdir(), "warden-baseline-"));
		db = openDb(join(dir, "warden.db"));
	});

	afterEach(() => {
		db.close();
		rmSync(dir, { recursive: true, force: true });
	});

	it("freezes run1_tokens and ratchets best_tokens downward only", () => {
		recordBaseline(db, "sql", "sql-01", 50_000, "t1");
		recordBaseline(db, "sql", "sql-01", 40_000, "t2");
		recordBaseline(db, "sql", "sql-01", 60_000, "t3");
		const baseline = getBaseline(db, "sql", "sql-01");
		expect(baseline?.run1_tokens).toBe(50_000);
		expect(baseline?.best_tokens).toBe(40_000);
		expect(baseline?.updated_at).toBe("t3");
	});
});
