import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
	compileMemoryMd,
	EnvironmentFailureError,
	type GoldenTask,
	goldenSuiteHash,
	isEnvironmentFailure,
	loadGoldenTasks,
	parseAgentDefinition,
	parseArgs,
	parseGoldenTask,
	passEnvironmentFailure,
	type RunResult,
	runSuite,
	type SuiteOptions,
	summarizeTask,
	totalTokens,
} from "../src/bench.js";
import {
	getBaseline,
	openDb,
	recordBaseline,
	type WardenDb,
} from "../src/db.js";
import { knownAgents } from "../src/registry.js";

describe("parseArgs", () => {
	it("parses agent, rule, runs, and task", () => {
		expect(
			parseArgs([
				"--agent",
				"sql",
				"--rule",
				"7",
				"--runs",
				"3",
				"--task",
				"sql-01",
			]),
		).toEqual({ agent: "sql", rule: 7, runs: 3, task: "sql-01" });
	});

	it("defaults to three runs and no rule", () => {
		expect(parseArgs(["--agent", "backend"])).toEqual({
			agent: "backend",
			rule: null,
			runs: 3,
			task: null,
		});
	});

	it("rejects unknown agents, flags, and bad runs", () => {
		expect(() => parseArgs(["--agent", "main"])).toThrow(/--agent/);
		expect(() => parseArgs(["--agent", "sql", "--frobnicate", "1"])).toThrow(
			/unknown flag/,
		);
		expect(() => parseArgs(["--agent", "sql", "--runs", "0"])).toThrow(
			/--runs/,
		);
	});
});

describe("golden task files", () => {
	it("parses frontmatter fields", () => {
		const task = parseGoldenTask(
			'---\nid: x-01\nagent: sql\nprompt: "Do the thing."\nsuccess_check: "true"\n---\nbody',
			"x.md",
		);
		expect(task).toMatchObject({
			id: "x-01",
			agent: "sql",
			prompt: "Do the thing.",
			successCheck: "true",
		});
	});

	it("rejects files missing required fields", () => {
		expect(() => parseGoldenTask("---\nid: x\n---\n", "x.md")).toThrow(/agent/);
		expect(() => parseGoldenTask("no frontmatter", "x.md")).toThrow(
			/frontmatter/,
		);
	});

	it("every shipped agent has a complete, well-formed golden suite (>=3 tasks, unique ids)", () => {
		for (const agent of knownAgents()) {
			const tasks = loadGoldenTasks(agent);
			// A complete suite is at least 3 tasks; suites may grow (only by
			// adding files — baselines are frozen), so this is a floor, not an
			// exact count.
			expect(tasks.length, agent).toBeGreaterThanOrEqual(3);
			const ids = new Set<string>();
			for (const task of tasks) {
				expect(task.agent).toBe(agent);
				expect(task.id).toMatch(new RegExp(`^${agent}-\\d+$`));
				expect(task.prompt.length).toBeGreaterThan(20);
				expect(task.successCheck.length).toBeGreaterThan(0);
				// Duplicate ids would silently collide on one frozen baseline.
				expect(ids.has(task.id), `duplicate task id ${task.id}`).toBe(false);
				ids.add(task.id);
			}
		}
	});

	it("the narrower split tasks parse and carry unique ids within their agent", () => {
		const splits: Array<{ agent: string; file: string }> = [
			{ agent: "sql", file: "../benchmarks/sql/golden-06.md" },
			{ agent: "sql", file: "../benchmarks/sql/golden-07.md" },
			{ agent: "testing", file: "../benchmarks/testing/golden-05.md" },
			{ agent: "testing", file: "../benchmarks/testing/golden-06.md" },
		];
		const byAgent = new Map<string, Set<string>>();
		for (const { agent, file } of splits) {
			const path = fileURLToPath(new URL(file, import.meta.url));
			const task = parseGoldenTask(readFileSync(path, "utf8"), path);
			expect(task.agent).toBe(agent);
			expect(task.id).toMatch(new RegExp(`^${agent}-\\d+$`));
			expect(task.prompt.length).toBeGreaterThan(20);
			expect(task.successCheck.length).toBeGreaterThan(0);
			const seen = byAgent.get(agent) ?? new Set<string>();
			expect(seen.has(task.id), `duplicate task id ${task.id}`).toBe(false);
			seen.add(task.id);
			byAgent.set(agent, seen);
		}
		// The added ids must also be unique against the rest of their live suite.
		for (const agent of ["sql", "testing"]) {
			const ids = loadGoldenTasks(agent).map((t) => t.id);
			expect(new Set(ids).size).toBe(ids.length);
		}
	});
});

describe("compileMemoryMd", () => {
	it("renders the generated header and one rule per line", () => {
		const memory = compileMemoryMd([{ body: "Rule A" }, { body: "Rule B" }]);
		expect(memory).toContain("GENERATED BY token-warden");
		expect(memory).toContain("- Rule A\n- Rule B");
	});
});

describe("totalTokens", () => {
	it("sums all four token counters", () => {
		expect(
			totalTokens({
				inputTokens: 1,
				outputTokens: 2,
				cacheCreation: 3,
				cacheRead: 4,
			}),
		).toBe(10);
	});
});

describe("summarizeTask", () => {
	it("averages completed runs only and flags >25% variance", () => {
		const summary = summarizeTask("t", [
			{ sessionId: "a", tokens: 100, completed: true },
			{ sessionId: "b", tokens: 200, completed: true },
			{ sessionId: "c", tokens: 9999, completed: false },
		]);
		expect(summary.meanCompletedTokens).toBe(150);
		expect(summary.highVariance).toBe(true);
	});

	it("does not flag close runs", () => {
		const summary = summarizeTask("t", [
			{ sessionId: "a", tokens: 100, completed: true },
			{ sessionId: "b", tokens: 110, completed: true },
		]);
		expect(summary.highVariance).toBe(false);
	});

	it("defaults weight to 1 and carries an explicit weight through", () => {
		const results = [{ sessionId: "a", tokens: 100, completed: true }];
		expect(summarizeTask("t", results).weight).toBe(1);
		expect(summarizeTask("t", results, 4).weight).toBe(4);
	});
});

describe("parseGoldenTask weight", () => {
	const base =
		'---\nid: sql-01\nagent: sql\nprompt: "Do the thing."\nsuccess_check: "true"';
	it("defaults an absent weight to 1", () => {
		expect(parseGoldenTask(`${base}\n---\nbody`, "x.md").weight).toBe(1);
	});
	it("parses a fractional weight", () => {
		expect(
			parseGoldenTask(`${base}\nweight: 2.5\n---\nbody`, "x.md").weight,
		).toBe(2.5);
	});
	it("rejects a zero, negative, or non-numeric weight", () => {
		expect(() =>
			parseGoldenTask(`${base}\nweight: 0\n---\nbody`, "x.md"),
		).toThrow(/weight/);
		expect(() =>
			parseGoldenTask(`${base}\nweight: -3\n---\nbody`, "x.md"),
		).toThrow(/weight/);
		expect(() =>
			parseGoldenTask(`${base}\nweight: x\n---\nbody`, "x.md"),
		).toThrow(/weight/);
	});
});

describe("baseline freezing", () => {
	let dir: string;
	let db: WardenDb;

	beforeEach(() => {
		dir = mkdtempSync(join(tmpdir(), "warden-baseline-"));
		db = openDb(join(dir, "warden.db"));
	});

	afterEach(() => {
		db.close();
		rmSync(dir, { recursive: true, force: true });
	});

	it("freezes run1_tokens and ratchets best_tokens downward only", () => {
		recordBaseline(db, "sql", "sql-01", 50_000, "t1");
		recordBaseline(db, "sql", "sql-01", 40_000, "t2");
		recordBaseline(db, "sql", "sql-01", 60_000, "t3");
		const baseline = getBaseline(db, "sql", "sql-01");
		expect(baseline?.run1_tokens).toBe(50_000);
		expect(baseline?.best_tokens).toBe(40_000);
		expect(baseline?.updated_at).toBe("t3");
	});
});

// Safety-critical: a benchmark must NEVER read or write the user's real
// ~/.claude/agent-memory. parseAgentDefinition enforces that by rewriting the
// memory scope to `project`, so MEMORY.md resolves inside the temp workdir.
describe("parseAgentDefinition (memory-scope isolation)", () => {
	const def = (frontmatter: string) =>
		`---\n${frontmatter}\n---\n\nYou are an agent.\n`;

	it("rewrites a user-scoped memory field to project", () => {
		const { content } = parseAgentDefinition(
			def("name: sql\nmemory: user\nmodel: sonnet"),
			"sql.md",
		);
		expect(content).toContain("memory: project");
		expect(content).not.toMatch(/^memory: user$/m);
	});

	it("rewrites any single-word scope (local) and is idempotent on project", () => {
		expect(
			parseAgentDefinition(def("memory: local"), "x.md").content,
		).toContain("memory: project");
		expect(
			parseAgentDefinition(def("memory: project"), "x.md").content,
		).toContain("memory: project");
	});

	it("tolerates no spacing after the colon", () => {
		expect(parseAgentDefinition(def("memory:user"), "x.md").content).toContain(
			"memory: project",
		);
	});

	it("throws when there is no memory frontmatter field to rewrite", () => {
		expect(() => parseAgentDefinition(def("name: sql"), "sql.md")).toThrow(
			/no "memory:" frontmatter/,
		);
		expect(() => parseAgentDefinition(def("name: sql"), "sql.md")).toThrow(
			/sql\.md/,
		);
	});

	it("extracts the model, defaulting to sonnet when absent", () => {
		expect(
			parseAgentDefinition(def("memory: user\nmodel: haiku"), "x").model,
		).toBe("haiku");
		expect(parseAgentDefinition(def("memory: user"), "x").model).toBe("sonnet");
	});

	it("preserves the rest of the definition body", () => {
		const { content } = parseAgentDefinition(def("memory: user"), "x.md");
		expect(content).toContain("You are an agent.");
	});
});

describe("goldenSuiteHash", () => {
	it("is a stable 12-char hex digest", () => {
		const h = goldenSuiteHash("sql");
		expect(h).toMatch(/^[0-9a-f]{12}$/);
		expect(goldenSuiteHash("sql")).toBe(h);
	});

	it("differs between agents whose suites differ", () => {
		expect(goldenSuiteHash("sql")).not.toBe(goldenSuiteHash("backend"));
	});
});

describe("environment-failure detection", () => {
	it("classifies only zero-ish-token failed runs as environment failures", () => {
		const run = (tokens: number, completed: boolean) => ({
			sessionId: "s",
			tokens,
			completed,
		});
		expect(isEnvironmentFailure(run(0, false))).toBe(true);
		expect(isEnvironmentFailure(run(999, false))).toBe(true);
		// At the floor the run burned real tokens: rule signal, not environment.
		expect(isEnvironmentFailure(run(1000, false))).toBe(false);
		expect(isEnvironmentFailure(run(40_000, false))).toBe(false);
		// A completed run is never an environment failure, whatever its cost.
		expect(isEnvironmentFailure(run(0, true))).toBe(false);
	});

	it("trips the pass-level check on a strict majority with a minimum count", () => {
		const pass = (envFailed: number, ok: number) => [
			summarizeTask("t1", [
				...Array.from({ length: envFailed }, (_, i) => ({
					sessionId: `f${i}`,
					tokens: 0,
					completed: false,
				})),
				...Array.from({ length: ok }, (_, i) => ({
					sessionId: `o${i}`,
					tokens: 50_000,
					completed: true,
				})),
			]),
		];
		// Exactly half is not a majority.
		expect(passEnvironmentFailure(pass(3, 3)).tripped).toBe(false);
		expect(passEnvironmentFailure(pass(4, 2)).tripped).toBe(true);
		// A majority below the minimum count (transient crashes) never trips.
		expect(passEnvironmentFailure(pass(2, 1)).tripped).toBe(false);
		expect(passEnvironmentFailure(pass(3, 2)).tripped).toBe(true);
		// The real quota death: 72 of 84 baseline runs failed.
		expect(passEnvironmentFailure(pass(72, 12)).tripped).toBe(true);
		expect(passEnvironmentFailure(pass(4, 2))).toMatchObject({
			envFailed: 4,
			total: 6,
		});
	});

	it("failed-with-tokens runs are not counted as environment failures", () => {
		const summaries = [
			summarizeTask("t1", [
				{ sessionId: "a", tokens: 40_000, completed: false },
				{ sessionId: "b", tokens: 45_000, completed: false },
				{ sessionId: "c", tokens: 42_000, completed: false },
				{ sessionId: "d", tokens: 41_000, completed: false },
			]),
		];
		expect(passEnvironmentFailure(summaries)).toMatchObject({
			envFailed: 0,
			total: 4,
			tripped: false,
		});
	});
});

describe("runSuite environment-failure streak abort", () => {
	let dir: string;
	let db: WardenDb;

	beforeEach(() => {
		dir = mkdtempSync(join(tmpdir(), "warden-bench-suite-"));
		db = openDb(join(dir, "warden.db"));
	});

	afterEach(() => {
		db.close();
		rmSync(dir, { recursive: true, force: true });
	});

	const tasks = (n: number): GoldenTask[] =>
		Array.from({ length: n }, (_, i) => ({
			id: `t${i + 1}`,
			agent: "sql",
			prompt: "do the thing",
			successCheck: "true",
			file: `t${i + 1}.md`,
			weight: 1,
		}));

	const options = (runs: number): SuiteOptions => ({
		rules: [],
		runs,
		recordBaselines: false,
		rulesetVersion: 0,
		label: "test-pass",
		config: "candidate",
		definitionOverride: { content: "agent", model: "sonnet" },
	});

	/** Fake runOnce returning scripted results in order; throws (RUN-ERROR
	 * path) when the scripted entry is "crash". */
	function scripted(script: (RunResult | "crash")[]): {
		single: () => RunResult;
		calls: () => number;
	} {
		let i = 0;
		return {
			single: (): RunResult => {
				const entry = script[i++];
				if (entry === undefined) throw new Error("script exhausted");
				if (entry === "crash") throw new Error("claude crashed");
				return entry;
			},
			calls: () => i,
		};
	}

	const envFail = (): RunResult => ({
		sessionId: "dead",
		tokens: 0,
		completed: false,
	});
	const ok = (): RunResult => ({
		sessionId: "ok",
		tokens: 50_000,
		completed: true,
	});

	it("throws EnvironmentFailureError after 4 consecutive zero-token failures and stops running", () => {
		const fake = scripted([envFail(), envFail(), envFail(), envFail(), ok()]);
		expect(() =>
			runSuite(db, "sql", tasks(3), options(2), fake.single as never),
		).toThrow(EnvironmentFailureError);
		// No fifth run was attempted after the abort.
		expect(fake.calls()).toBe(4);
	});

	it("carries diagnostics (counts, streak, partial summaries) on the error", () => {
		const fake = scripted([ok(), envFail(), envFail(), envFail(), envFail()]);
		try {
			runSuite(db, "sql", tasks(3), options(2), fake.single as never);
			expect.unreachable("should have thrown");
		} catch (err) {
			if (!(err instanceof EnvironmentFailureError)) throw err;
			expect(err.info).toMatchObject({
				agent: "sql",
				label: "test-pass",
				envFailed: 4,
				total: 5,
				streak: 4,
			});
			expect(err.info.partial.length).toBeGreaterThan(0);
		}
	});

	it("a completed run resets the streak", () => {
		// fail,fail,fail,ok | fail,fail,fail,fail -> aborts on run 8, not 4.
		const fake = scripted([
			envFail(),
			envFail(),
			envFail(),
			ok(),
			envFail(),
			envFail(),
			envFail(),
			envFail(),
		]);
		expect(() =>
			runSuite(db, "sql", tasks(2), options(4), fake.single as never),
		).toThrow(EnvironmentFailureError);
		expect(fake.calls()).toBe(8);
	});

	it("a failed run that burned real tokens resets the streak (rule signal, not environment)", () => {
		const ruleFail = (): RunResult => ({
			sessionId: "broke",
			tokens: 40_000,
			completed: false,
		});
		const fake = scripted([
			envFail(),
			envFail(),
			envFail(),
			ruleFail(),
			ok(),
			ok(),
		]);
		const summaries = runSuite(
			db,
			"sql",
			tasks(3),
			options(2),
			fake.single as never,
		);
		expect(summaries).toHaveLength(3);
		expect(fake.calls()).toBe(6);
	});

	it("crash-thrown runs (RUN-ERROR) count toward the streak", () => {
		const fake = scripted(["crash", "crash", "crash", "crash", ok()]);
		expect(() =>
			runSuite(db, "sql", tasks(3), options(2), fake.single as never),
		).toThrow(EnvironmentFailureError);
		expect(fake.calls()).toBe(4);
	});

	it("a single broken run still does not abort the suite", () => {
		const fake = scripted([ok(), "crash", ok(), ok()]);
		const summaries = runSuite(
			db,
			"sql",
			tasks(2),
			options(2),
			fake.single as never,
		);
		expect(summaries).toHaveLength(2);
		const failed = summaries
			.flatMap((s) => s.results)
			.filter((r) => !r.completed);
		expect(failed).toHaveLength(1);
	});
});
