import {
	existsSync,
	mkdtempSync,
	readdirSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
	extractFirstUserPrompt,
	extractTaskDrafts,
	main,
	parseSampleArgs,
	renderDraft,
} from "../src/sample-tasks.js";

function userLine(content: unknown): string {
	return JSON.stringify({ type: "user", message: { role: "user", content } });
}

describe("extractFirstUserPrompt", () => {
	it("pulls a string user message", () => {
		const jsonl = userLine("Add a unique index on the orders.email column.");
		expect(extractFirstUserPrompt(jsonl)).toBe(
			"Add a unique index on the orders.email column.",
		);
	});

	it("pulls text blocks from array content", () => {
		const jsonl = userLine([
			{ type: "text", text: "Optimize the slow report query in reports.sql." },
		]);
		expect(extractFirstUserPrompt(jsonl)).toContain("Optimize the slow report");
	});

	it("skips short, tool-envelope, and caveat noise, returns the real prompt", () => {
		const jsonl = [
			userLine("ok"),
			userLine("<tool_result>123</tool_result>"),
			userLine("Caveat: generated by a local command"),
			userLine("Refactor the migration runner to be idempotent and safe."),
		].join("\n");
		expect(extractFirstUserPrompt(jsonl)).toBe(
			"Refactor the migration runner to be idempotent and safe.",
		);
	});

	it("returns null when there is no usable prompt", () => {
		expect(extractFirstUserPrompt(userLine("ok"))).toBeNull();
		expect(extractFirstUserPrompt("not json\n{bad")).toBeNull();
	});
});

describe("extractTaskDrafts", () => {
	it("de-duplicates near-identical prompts, keeps distinct ones", () => {
		const drafts = extractTaskDrafts([
			{
				sessionId: "a",
				jsonl: userLine("Add a unique index on orders.email."),
			},
			{
				sessionId: "b",
				jsonl: userLine("Add a unique index on orders.email please."),
			},
			{
				sessionId: "c",
				jsonl: userLine("Write a migration to backfill the totals column."),
			},
		]);
		expect(drafts).toHaveLength(2);
		expect(drafts[0]?.sourceSession).toBe("a");
	});

	it("ignores transcripts with no usable prompt", () => {
		const drafts = extractTaskDrafts([
			{ sessionId: "x", jsonl: userLine("ok") },
		]);
		expect(drafts).toHaveLength(0);
	});
});

describe("renderDraft", () => {
	it("emits a task file with the prompt and a TODO success check", () => {
		const md = renderDraft("sql", 1, {
			prompt: "Optimize the slow report query.",
			sourceSession: "sess-1",
		});
		expect(md).toContain('id: "sql-draft-01"');
		expect(md).toContain('agent: "sql"');
		expect(md).toContain("Optimize the slow report query.");
		expect(md).toMatch(/success_check: "TODO/);
		expect(md).toContain("sess-1");
	});
});

describe("parseSampleArgs", () => {
	it("requires a valid agent and a --from", () => {
		expect(() => parseSampleArgs(["--from", "x"])).toThrow(/--agent/);
		expect(() => parseSampleArgs(["--agent", "sql"])).toThrow(/--from/);
	});

	it("defaults --out under benchmarks/<agent>/drafts", () => {
		const args = parseSampleArgs(["--agent", "sql", "--from", "dir"]);
		expect(args.out).toMatch(/benchmarks\/sql\/drafts$/);
	});
});

describe("sample-tasks main()", () => {
	let dir: string;

	beforeEach(() => {
		dir = mkdtempSync(join(tmpdir(), "warden-sample-main-"));
		vi.spyOn(console, "log").mockImplementation(() => {});
	});
	afterEach(() => {
		vi.restoreAllMocks();
		rmSync(dir, { recursive: true, force: true });
	});

	it("writes draft files from a directory of transcripts", () => {
		writeFileSync(
			join(dir, "sess1.jsonl"),
			userLine("Add a composite index on (tenant_id, created_at)."),
		);
		const out = join(dir, "drafts");
		expect(main(["--agent", "sql", "--from", dir, "--out", out])).toBe(0);
		const files = readdirSync(out);
		expect(files).toHaveLength(1);
		expect(files[0]).toMatch(/sql-draft-01\.md/);
	});

	it("reports and writes nothing when there is no usable prompt", () => {
		const file = join(dir, "empty.jsonl");
		writeFileSync(file, userLine("ok"));
		const out = join(dir, "drafts");
		expect(main(["--agent", "sql", "--from", file, "--out", out])).toBe(0);
		expect(existsSync(out)).toBe(false);
	});
});
