import {
	existsSync,
	mkdtempSync,
	readdirSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
	extractFirstUserPrompt,
	extractTaskDrafts,
	main,
	parseSampleArgs,
	redactSensitive,
	renderDraft,
	sanitizeDraftPrompt,
} from "../src/sample-tasks.js";

function userLine(content: unknown): string {
	return JSON.stringify({ type: "user", message: { role: "user", content } });
}

describe("extractFirstUserPrompt", () => {
	it("pulls a string user message", () => {
		const jsonl = userLine("Add a unique index on the orders.email column.");
		expect(extractFirstUserPrompt(jsonl)).toBe(
			"Add a unique index on the orders.email column.",
		);
	});

	it("pulls text blocks from array content", () => {
		const jsonl = userLine([
			{ type: "text", text: "Optimize the slow report query in reports.sql." },
		]);
		expect(extractFirstUserPrompt(jsonl)).toContain("Optimize the slow report");
	});

	it("skips short, tool-envelope, and caveat noise, returns the real prompt", () => {
		const jsonl = [
			userLine("ok"),
			userLine("<tool_result>123</tool_result>"),
			userLine("Caveat: generated by a local command"),
			userLine("Refactor the migration runner to be idempotent and safe."),
		].join("\n");
		expect(extractFirstUserPrompt(jsonl)).toBe(
			"Refactor the migration runner to be idempotent and safe.",
		);
	});

	it("returns null when there is no usable prompt", () => {
		expect(extractFirstUserPrompt(userLine("ok"))).toBeNull();
		expect(extractFirstUserPrompt("not json\n{bad")).toBeNull();
	});
});

describe("extractTaskDrafts", () => {
	it("de-duplicates near-identical prompts, keeps distinct ones", () => {
		const drafts = extractTaskDrafts([
			{
				sessionId: "a",
				jsonl: userLine("Add a unique index on orders.email."),
			},
			{
				sessionId: "b",
				jsonl: userLine("Add a unique index on orders.email please."),
			},
			{
				sessionId: "c",
				jsonl: userLine("Write a migration to backfill the totals column."),
			},
		]);
		expect(drafts).toHaveLength(2);
		expect(drafts[0]?.sourceSession).toBe("a");
	});

	it("ignores transcripts with no usable prompt", () => {
		const drafts = extractTaskDrafts([
			{ sessionId: "x", jsonl: userLine("ok") },
		]);
		expect(drafts).toHaveLength(0);
	});
});

describe("renderDraft", () => {
	it("emits a task file with the prompt and a TODO success check", () => {
		const md = renderDraft("sql", 1, {
			prompt: "Optimize the slow report query.",
			sourceSession: "sess-1",
		});
		expect(md).toContain('id: "sql-draft-01"');
		expect(md).toContain('agent: "sql"');
		expect(md).toContain("Optimize the slow report query.");
		expect(md).toMatch(/success_check: "TODO/);
		expect(md).toContain("sess-1");
	});

	it("marks the draft as UNVERIFIED and not part of the suite", () => {
		const md = renderDraft("sql", 2, {
			prompt: "Optimize the slow report query.",
			sourceSession: "sess-1",
		});
		expect(md).toContain("UNVERIFIED DRAFT");
		expect(md).toContain("NOT part of the golden suite");
		// It says how to promote it, and that leaving it here is inert.
		expect(md).toContain("golden-NN.md");
	});

	/** The session id is a filename off disk. It lands inside an HTML comment,
	 * so it must not be able to close that comment and inject markdown into a
	 * file the user is invited to commit. */
	it("defuses a session id that would escape the provenance comment", () => {
		const md = renderDraft("sql", 1, {
			prompt: "Optimize the slow report query.",
			sourceSession: "evil--><script>x</script>\nid: hijacked",
		});
		expect(md).toContain("Sampled from real session evil->");
		expect(md).not.toContain("-->\x3cscript");
		expect(md).not.toContain("\nid: hijacked");
		// The banner is still one intact comment ending where it should.
		expect(md).toContain("before this file goes anywhere. -->");
	});
});

// These prompts come verbatim out of the user's own transcripts, and the
// drafts are written into the user's repo for them to review and commit.
describe("redaction of drafted prompts", () => {
	it("collapses this machine's real home directory to ~", () => {
		const out = redactSensitive(
			`Fix the query in ${homedir()}/work/app/db.sql`,
		);
		expect(out).not.toContain(homedir());
		expect(out).toContain("~/work/app/db.sql");
	});

	it("collapses other people's absolute home paths to ~", () => {
		expect(redactSensitive("open /Users/jane.doe/Desktop/notes.md")).toBe(
			"open ~/Desktop/notes.md",
		);
		expect(redactSensitive("open /home/bob/src/main.rs")).toBe(
			"open ~/src/main.rs",
		);
	});

	it("redacts credential-shaped strings", () => {
		const cases = [
			"sk-ant-api03-AAAAAAAAAAAAAAAAAAAAAAAAAA",
			"ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
			"github_pat_11ABCDEFG0aaaaaaaaaaaaaaaaaaaa",
			"AKIAIOSFODNN7EXAMPLE",
			"AIzaSyA0000000000000000000000000000000",
			"xoxb-1234567890-abcdefghijkl",
			"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dBjftJeZ4CVPmB92K27u",
			"Authorization: Bearer abcdefghijklmnopqrstuvwxyz",
			"DB_PASSWORD=hunter2hunter2",
			"api_key: 0123456789abcdef",
		];
		for (const secret of cases) {
			const out = redactSensitive(`Use ${secret} to connect.`);
			expect(out, secret).toContain("[REDACTED]");
			expect(out, secret).not.toContain(secret);
		}
		expect(redactSensitive("-----BEGIN RSA PRIVATE KEY-----")).toBe(
			"[REDACTED]",
		);
	});

	it("redacts email addresses", () => {
		expect(redactSensitive("ping alice.smith@example.com about it")).toBe(
			"ping [EMAIL] about it",
		);
	});

	it("leaves ordinary engineering prose untouched", () => {
		for (const prompt of [
			"Add a composite index on (tenant_id, created_at).",
			"Optimize the slow report query in reports.sql.",
			"Refactor the migration runner to be idempotent and safe.",
			"Rename src/token-warden/db.ts and update the imports.",
		]) {
			expect(redactSensitive(prompt)).toBe(prompt);
		}
	});

	it("redacts before clamping, so a secret cannot survive by being cut in half", () => {
		const secret = "ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
		const prompt = `${"pad ".repeat(160)}${secret} done`;
		const out = sanitizeDraftPrompt(prompt);
		expect(out).not.toContain("ghp_");
	});

	it("keeps the frontmatter scalar parseable: no quotes, no trailing backslash", () => {
		const md = renderDraft("sql", 1, {
			prompt: 'Run "SELECT 1" against C:\\data\\db\\',
			sourceSession: "s",
		});
		const line = md.split("\n").find((l) => l.startsWith("prompt:")) as string;
		expect(line.startsWith('prompt: "')).toBe(true);
		expect(line.endsWith('"')).toBe(true);
		expect(line.slice('prompt: "'.length, -1)).not.toContain('"');
		expect(line).not.toContain("\\");
	});

	it("strips ANSI and control characters out of an untrusted prompt", () => {
		const out = sanitizeDraftPrompt(
			"Fix \u001b[31mthe\u001b[0m query\u0007 now\nand stop",
		);
		expect(out).toBe("Fix the query now and stop");
	});

	it("the rendered draft never contains the user's home path", () => {
		const md = renderDraft("sql", 1, {
			prompt: `Read ${homedir()}/secrets/prod.env and fix the schema`,
			sourceSession: "s",
		});
		expect(md).not.toContain(homedir());
	});
});

describe("parseSampleArgs", () => {
	it("requires a valid agent and a --from", () => {
		expect(() => parseSampleArgs(["--from", "x"])).toThrow(/--agent/);
		expect(() => parseSampleArgs(["--agent", "sql"])).toThrow(/--from/);
	});

	it("defaults --out under benchmarks/<agent>/drafts", () => {
		const args = parseSampleArgs(["--agent", "sql", "--from", "dir"]);
		expect(args.out).toMatch(/benchmarks\/sql\/drafts$/);
	});
});

describe("sample-tasks main()", () => {
	let dir: string;

	beforeEach(() => {
		dir = mkdtempSync(join(tmpdir(), "warden-sample-main-"));
		vi.spyOn(console, "log").mockImplementation(() => {});
	});
	afterEach(() => {
		vi.restoreAllMocks();
		rmSync(dir, { recursive: true, force: true });
	});

	it("writes draft files from a directory of transcripts", () => {
		writeFileSync(
			join(dir, "sess1.jsonl"),
			userLine("Add a composite index on (tenant_id, created_at)."),
		);
		const out = join(dir, "drafts");
		expect(main(["--agent", "sql", "--from", dir, "--out", out])).toBe(0);
		const files = readdirSync(out);
		expect(files).toHaveLength(1);
		expect(files[0]).toMatch(/sql-draft-01\.md/);
	});

	it("reports and writes nothing when there is no usable prompt", () => {
		const file = join(dir, "empty.jsonl");
		writeFileSync(file, userLine("ok"));
		const out = join(dir, "drafts");
		expect(main(["--agent", "sql", "--from", file, "--out", out])).toBe(0);
		expect(existsSync(out)).toBe(false);
	});

	it("writes nothing for a directory with no transcripts at all", () => {
		const out = join(dir, "drafts");
		expect(main(["--agent", "sql", "--from", dir, "--out", out])).toBe(0);
		expect(existsSync(out)).toBe(false);
	});

	it("gives a clear error when --from does not exist", () => {
		expect(() =>
			main(["--agent", "sql", "--from", join(dir, "missing")]),
		).toThrow(/--from path not found/);
	});
});
