#!/usr/bin/env bash
#
# Self-driving overnight burn. Works through a queue of test chunks across
# multiple quota windows: when a chunk's quota probe fails (window exhausted),
# it sleeps ~5h and retries after the reset, then continues. Detached/nohup-safe
# — survives this terminal closing; only needs the Mac awake (caffeinate).
# Writes validation/results/SUMMARY.txt for you to read in the morning.
#
set -uo pipefail
cd "$(dirname "$0")/.."
RESET_SLEEP="${RESET_SLEEP:-18300}"   # ~5h05m between quota windows
MAX_WAITS="${MAX_WAITS:-3}"           # give up a chunk after this many resets
OLOG="validation/results/overnight.log"
mkdir -p validation/results
exec >>"${OLOG}" 2>&1
echo "═══════ overnight start $(date) ═══════"

# Never run concurrently with an in-flight burn (e.g. the current Track 2 run).
echo "waiting for any in-flight burn-all.sh to finish…"
while pgrep -f "validation/burn-all.sh" >/dev/null 2>&1; do sleep 120; done
echo "clear — starting queue $(date)"

# Run one chunk; on quota-out (probe failed at start) sleep for the reset and
# retry. A chunk that runs (full or partial) counts as done and we move on.
run_chunk() {
	local label="$1"; shift   # remaining args: VAR=VAL …
	local waits=0
	while :; do
		echo "── chunk ${label} (waits=${waits}) $(date) ──"
		env "$@" ./validation/burn-all.sh || true
		local D; D=$(ls -dt validation/results/burn-* 2>/dev/null | head -1)
		if grep -q "BURN_RESULT=quota-unavailable" "${D}/run.log" 2>/dev/null; then
			waits=$((waits + 1))
			if [ "${waits}" -gt "${MAX_WAITS}" ]; then
				echo "${label}: gave up after ${MAX_WAITS} quota waits"; return 1
			fi
			echo "${label}: quota window exhausted; sleeping ${RESET_SLEEP}s for reset"
			sleep "${RESET_SLEEP}"
		else
			echo "${label}: ran → $(basename "${D}")"; return 0
		fi
	done
}

# The queue — highest-value untested chunks first. Each is ~one quota window.
# sql-realwork is THE learning test (now with correct sql attribution); run it
# first so a fresh window goes to it, not the lower-value controlled chunks.
run_chunk "sql-realwork"        BURN_T1_AGENTS=
run_chunk "testing-controlled"  BURN_T1_AGENTS=testing BURN_SKIP_T2=1
run_chunk "backend-controlled"  BURN_T1_AGENTS=backend BURN_SKIP_T2=1

# Compile a single human-readable summary of every run captured tonight.
SUM="validation/results/SUMMARY.txt"
{
	echo "token-warden overnight burn summary — $(date)"
	echo "(generated by validation/burn-overnight.sh)"
	echo
	for D in $(ls -dt validation/results/burn-*); do
		echo "### $(basename "${D}")"
		grep -aE "Track [12]|→ (ACTIVE|EVICTED)|Compiled .* active|No candidates|distillers|claude session failed|BURN_RESULT" \
			"${D}/run.log" 2>/dev/null | sed 's/^/  /'
		if [ -f "${D}/status-realwork-v1.txt" ]; then
			grep -aA1 "Real-work learning (avg" "${D}/status-realwork-v1.txt" 2>/dev/null | sed 's/^/  RW: /'
		fi
		echo
	done
} > "${SUM}"
echo "═══════ overnight done $(date) — summary → ${SUM} ═══════"
