/**
 * The single writer of agent memory.
 *
 * `MEMORY.md` is a BUILD ARTIFACT (invariant #2): compiled wholesale from the
 * ledger, overwritten atomically, never hand-edited. It is also the highest-
 * consequence file the plugin produces — it is injected into the agent's prompt
 * in every future session, and nothing validates it on read.
 *
 * Extracted from `select.ts` so the two small governance CLIs that also write
 * it (`/warden-protect` and `/warden-scope`, ~110 lines each) no longer import
 * the entire rule selector — and through it `bench.ts` and `pricing.ts` — to
 * reach one function. `compileMemoryMd` came from `bench.ts`, which needs it to
 * install memory into a throwaway fixture; both callers now share one
 * definition of what the compiled bytes are.
 */
import {
	existsSync,
	mkdirSync,
	readFileSync,
	renameSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import {
	bumpRulesetVersion,
	getActiveRules,
	type RuleRow,
	type WardenDb,
} from "./db.js";
import { packRules } from "./knapsack.js";
import { trigramSimilarity } from "./rules.js";
import { displayText } from "./sanitize.js";
import { memoryContextBudget } from "./stats.js";

/** Compile rule bodies into the MEMORY.md injected into the agent's prompt.
 * Overwritten wholesale by the selector — never hand-edited (invariant #2). A
 * scoped rule is rendered with a "(when <scope>)" prefix so the agent applies it
 * only in that context; unscoped rules are always-on. */
export function compileMemoryMd(
	rules: readonly (Pick<RuleRow, "body"> & { scope?: string | null })[],
): string {
	const lines = rules.map((rule) =>
		rule.scope ? `- (when ${rule.scope}) ${rule.body}` : `- ${rule.body}`,
	);
	return [
		"<!-- GENERATED BY token-warden — do not hand-edit -->",
		"# Efficiency rules",
		"",
		...lines,
		"",
	].join("\n");
}

/** Where compiled agent memory lives. Overridable for tests so they never
 * touch the real ~/.claude/agent-memory. */
export function memoryFilePath(agent: string): string {
	const base =
		process.env.TOKEN_WARDEN_MEMORY_DIR ??
		join(homedir(), ".claude", "agent-memory");
	return join(base, agent, "MEMORY.md");
}

/** Ceilings on what one compiled bullet may carry. Every sanctioned insertion
 * path (distiller, compression rewriter, ledger import) already caps a rule
 * body at 200 characters, so the body ceiling is pure headroom; a rule SCOPE
 * has no input ceiling at all (it arrives from the /warden-scope CLI), which is
 * why it gets its own. */
const MEMORY_BODY_MAX = 400;
const MEMORY_SCOPE_MAX = 200;

/**
 * SECURITY: MEMORY.md is the one artifact this tool writes straight into a real
 * agent's prompt, every session, and its format is one bullet per rule. A
 * newline anywhere in a body or a scope therefore forges additional bullets
 * that read exactly like measured rules — prompt injection into the agent this
 * tool is supposed to be making cheaper.
 *
 * Bodies are validated single-line at every insertion path (distill, compress,
 * adopt), but a scope is stored VERBATIM by design (src/scope.ts: the stored
 * value is what gets compiled), so nothing guarded this write. Defense in depth
 * belongs at the writer, not only at the writers' inputs: everything crossing
 * into compiled memory goes through `displayText`, the repo's single
 * sanitization chokepoint, which strips control/escape/invisible characters and
 * collapses the value onto one line. It is a no-op on a well-formed rule.
 */
function memorySafeRules(rules: RuleRow[]): RuleRow[] {
	return rules.map((rule) => ({
		...rule,
		body: displayText(rule.body, MEMORY_BODY_MAX),
		scope:
			rule.scope === null ? null : displayText(rule.scope, MEMORY_SCOPE_MAX),
	}));
}

/**
 * Trim an active rule set to fit a context budget, by the submodular knapsack
 * (`knapsack.ts`).
 *
 * UNSET BY DEFAULT, and when unset this returns the rules untouched — so every
 * existing installation compiles byte-identical memory. That default is not
 * timidity: a budget is a claim about how much context an agent can spend on
 * memory, and only the operator knows it.
 *
 * When a budget IS set, this is the counterweight to a permissive gate. The
 * v1.0.0 stream calibration found false positives ~191x cheaper than false
 * negatives *while context is free*, and concluded "permissive at the gate,
 * strict at the packer" — the whole force of which depends on a packer actually
 * existing. Admission asks whether a rule pays its own rent; this asks which
 * rules to carry when the window will not hold them all.
 *
 * Protected rules are FORCED in, which is where that constraint belongs: it is
 * a statement about the solution set, not about a rule's individual merit.
 *
 * SIMILARITY IS TRIGRAM OVERLAP BETWEEN RULE BODIES, which is what makes the
 * submodular half of the packer load-bearing rather than decorative. Under the
 * module's independent default the objective collapses to a plain sum and the
 * whole facility-location construction does nothing; with a real similarity,
 * two rules that say nearly the same thing stop each counting in full.
 *
 * `trigramSimilarity` satisfies what the objective needs -- it lands in [0, 1],
 * it is symmetric, and it is 1 on the diagonal -- and it is not a new
 * assumption smuggled in here: `distill.ts` already uses this exact measure to
 * decide that two rules ARE the same rule, deduping candidates above 0.85. This
 * reuses a judgement the project already makes and already tests.
 *
 * THE HONEST LIMIT. Trigram overlap measures TEXTUAL similarity, not overlap in
 * what two rules actually save. Two rules can be worded quite differently and
 * address the same waste, which this will miss, or be worded alike and address
 * different waste, which this will over-discount. It is a proxy. It is a better
 * proxy than assuming independence, which is the alternative and is known to be
 * false -- but measuring real pairwise savings overlap is a token burn nobody
 * has run, and this stays a proxy until someone does.
 */
function packToBudget(rules: RuleRow[]): RuleRow[] {
	const budget = memoryContextBudget();
	if (budget === null) return rules;

	const candidates = rules.map((rule) => ({
		id: String(rule.id),
		contextCost: rule.context_cost,
		// A rule with no recorded delta (authored, or migrated from before
		// receipts) contributes no measured saving, so the knapsack ranks it
		// last rather than guessing on its behalf. A rule on probation carries a
		// NEGATIVE delta and is still active by design; the packer clamps that to
		// zero, because a negative mode weight would break the objective it
		// proves a bound against (knapsack.ts, non-negativity precondition).
		saving: rule.measured_delta ?? 0,
		forced: rule.protected === 1,
	}));

	// Precomputed once. `trigramSimilarity` rebuilds both trigram sets on every
	// call, and greedy asks for O(n^2) similarities per selection round, so
	// calling it directly would recompute the same sets a cubic number of times.
	const bodyById = new Map(rules.map((r) => [String(r.id), r.body]));
	const matrix = new Map<string, number>();
	for (const a of candidates) {
		for (const b of candidates) {
			matrix.set(
				JSON.stringify([a.id, b.id]),
				trigramSimilarity(bodyById.get(a.id) ?? "", bodyById.get(b.id) ?? ""),
			);
		}
	}

	const { chosen } = packRules(
		candidates,
		budget,
		(a, m) => matrix.get(JSON.stringify([a.id, m.id])) ?? 0,
	);

	// Preserve the caller's ordering rather than greedy's selection order: the
	// compiled file is read by a human as often as by an agent, and a memory
	// file that reshuffles itself on every recompile is a diff nobody can review.
	const keep = new Set(chosen);
	return rules.filter((rule) => keep.has(String(rule.id)));
}

/** The exact bytes the agent's MEMORY.md should hold for a rule set. */
function compiledMemoryFor(db: WardenDb, agent: string): string {
	return compileMemoryMd(
		packToBudget(memorySafeRules(getActiveRules(db, agent))),
	);
}

/**
 * Replace a file atomically: write a sibling temp file, then rename over the
 * target. `writeFileSync` truncates first, so a crash, a SIGKILL or ENOSPC
 * mid-write leaves a TRUNCATED MEMORY.md — and that file is injected into the
 * agent's prompt every subsequent session with nothing validating it on read.
 * A half-written rule is an instruction fragment the agent will try to follow.
 * rename(2) within a directory is atomic, so a reader sees either the old file
 * or the new one, never a fragment.
 */
function writeFileAtomic(path: string, content: string): void {
	const temp = `${path}.tmp-${process.pid}`;
	try {
		writeFileSync(temp, content);
		renameSync(temp, path);
	} catch (err) {
		rmSync(temp, { force: true });
		throw err;
	}
}

/** Recompile the agent's MEMORY.md from its current active rule set (including
 * protected rules) and bump the ruleset version. The single writer of agent
 * memory — shared by the selector and the protect command so the file is always
 * the wholesale, never-hand-edited artifact (invariant #2).
 *
 * The read, the write and the version bump are one IMMEDIATE transaction: the
 * compiled file and the version number stamped on it must describe the same
 * rule set even when a second warden process is deciding rules concurrently
 * (the DB runs in WAL mode, so it can be). */
export function compileActiveMemory(db: WardenDb, agent: string): number {
	const memoryPath = memoryFilePath(agent);
	mkdirSync(dirname(memoryPath), { recursive: true });
	return db
		.transaction(() => {
			writeFileAtomic(memoryPath, compiledMemoryFor(db, agent));
			return bumpRulesetVersion(db, agent, new Date().toISOString());
		})
		.immediate();
}

/**
 * Self-heal DB-vs-memory drift before measuring anything.
 *
 * Each rule's fate is committed as it is decided, but memory is compiled once
 * at the end of an invocation — so an interrupted or crashed /warden-select
 * leaves a rule `active` in the DB but absent from MEMORY.md, or (the expensive
 * direction) `evicted` in the DB while the agent keeps reading it and paying
 * its rent every session, forever, because nothing ever recompiles.
 *
 * Recompiling only on an actual content mismatch, rather than unconditionally,
 * is deliberate: `compileActiveMemory` bumps the ruleset version, and a version
 * bump on every invocation would churn a counter that receipts, /warden-status
 * and the run history all segment on, and would rewrite a file the agent's
 * prompt cache is keyed on, for no change. Comparing first costs one read.
 *
 * Returns the version compiled when drift was healed, else null.
 */
export function healMemoryDrift(db: WardenDb, agent: string): number | null {
	const memoryPath = memoryFilePath(agent);
	const expected = compiledMemoryFor(db, agent);
	const actual = existsSync(memoryPath)
		? readFileSync(memoryPath, "utf8")
		: null;
	if (actual === expected) return null;
	// No rules and no file is not drift, it is a fresh install: writing an empty
	// memory file (and burning ruleset v1 on it) would be noise.
	if (actual === null && getActiveRules(db, agent).length === 0) return null;
	return compileActiveMemory(db, agent);
}
